// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ISpooferSystem {
  error SpoofedFunctionSelectorNotFound(bytes4 functionSelector);
  error SpooferResourceNotFound(string resource);

  function spoofCall(bytes memory callBytes, address spoofedSender) external payable returns (bytes memory);
}
